# -*- coding: utf-8 -*-
"""idft.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fYPYLlTvwEDTvL3F0abH0pY5Hhf_kmCd
"""

import numpy as np

def idft(x):
    x = np.array(x)
    f = []
    M = x.size
    for i in range(M):
      val = 0
      for j in range(M):
        val += x[j]*np.exp(1j*2*np.pi*j*i/M)
      f.append(val/M)
    
    return f